In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]

[1 2 3 4 5]


In [3]:
arr = np.array([1, 2, 3, 4, 5])

# Indexing
print(arr[0])  # 1
print(arr[-1])  # 5

1
5


In [4]:
print(arr[1:3])  # [2 3]
print(arr[:3])  # [1 2 3]
print(arr[2:])  # [3 4 5]

[2 3]
[1 2 3]
[3 4 5]


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [6]:
print(arr1 + arr2)  # [5 7 9]
print(arr1 * arr2)  # [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [7]:
print(np.add(arr1, arr2))  # [5 7 9]
print(np.multiply(arr1, arr2))  # [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [8]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  # [[19 22], [43 50]]

[[19 22]
 [43 50]]


In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 3.0
print(np.median(arr))  # 3.0
print(np.std(arr))  # 1.4142135623730951

3.0
3.0
1.4142135623730951


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [11]:
print(np.reshape(arr, (2, 3))) 

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[1, 2], [3, 4]])

In [13]:
print(np.transpose(arr))

[[1 3]
 [2 4]]


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [15]:
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2)) 

[array([1, 2, 3]), array([4, 5, 6])]
